version: '3.1'

services:
    postgres:
        image: postgres
        volumes:
            - ./pgdb/:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
          POSTGRES_DB: 'db_name'
          POSTGRES_USER: 'user_name'
          POSTGRES_PASSWORD: '123'

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080 

    redis:
      image: redis
      restart: always
      ports:
        - "6379:6379"